ReservationApp/ReservationApp/Models/Role.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationApp.Models
{
    public class Role
    {
        [Required(ErrorMessage = "The role name field is required !")]
        [Display(Name = "Enter the name")]
        public string RoleName { get; set; }
    }
}

ReservationApp/ReservationApp/Models/ViewModels/EditUsersRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationApp.Models.ViewModels
{
    public class EditUsersRoleViewModel
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public bool IsSelected { get; set; }
    }
}

ReservationApp/ReservationApp/Controllers/RoleController.cs
using ReservationApp.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using ReservationApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationApp.Controllers
{
    // [Authorize(Roles = "Admin")]
    [AllowAnonymous]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<AppUser> userManager;
        private readonly ILogger<RoleController> logger;
        public RoleController(RoleManager<IdentityRole> roleManager,
                              UserManager<AppUser> userManager,
                              ILogger<RoleController> logger)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.logger = logger;
        }

        // actions

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Role model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole()
                {
                    Name = model.RoleName
                };

                IdentityResult result = await this.roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }


        [HttpGet]
        public IActionResult Index()
        {
            var roles = this.roleManager.Roles;
            return View(roles);
        }



        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id is null)
            {
                return View("../Error/NotFound", "Please add the role Id in URL");
            }
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role is null)
            {
                return View("../Error/NotFound", $"The role Id : {id} cannot be found");
            }

            EditRoleViewModel model = new EditRoleViewModel()
            {
                Id = role.Id,
                RoleName = role.Name,
                Users = new List<string>()  // pour recuperer ds cette list les users de ce role
            };

            foreach (AppUser user in await userManager.Users.ToListAsync()) // userManager.Users is not awaitble so change to (await userManager.Users.ToListAsync())
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }
            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Edit(EditRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByIdAsync(model.Id);
                if (role is null)
                {
                    return View("../Error/NotFound", $"The role Id : {model.Id} cannot be found");
                }
                role.Name = model.RoleName;

                IdentityResult result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);

        }



        [HttpGet]
        public IActionResult Delete()
        {
            return RedirectToAction("Index");
        }



        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {

            IdentityRole role = await roleManager.FindByIdAsync(id);


            try
            {
                if (!(role is null))
                {
                    IdentityResult result = await roleManager.DeleteAsync(role);

                    if (!result.Succeeded)
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
                else
                {
                    return View("../Error/NotFound", $"The role Id : {id} cannot be found");

                }
                return RedirectToAction("Index");

            }
            catch (DbUpdateException ex)
            {
                this.logger.LogError(ex.Message);
                ViewBag.Error = "Delete Role";
                string errorMessage = role.Name + " role is in use , so this role cannot be deleted as there users in this role." +
                    "if you want to delete this role, " +
                    "please remove the users from the role and then try to delete ";
                return View("Error", errorMessage);

            }






        }


        [HttpGet]
        public async Task<IActionResult> EditUsersRole(string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
            {
                return View("../Error/NotFound", $"The role must be exist and not empty in Url");

            }
            var role = await roleManager.FindByIdAsync(roleId);
            if (role is null)
            {
                return View("../Error/NotFound", $"The role Id : {role.Id} cannot be found");
            }

            var Models = new List<EditUsersRoleViewModel>();

            foreach (var user in await userManager.Users.ToListAsync())
            {
                EditUsersRoleViewModel model = new EditUsersRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    //IsSelected = false
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.IsSelected = true;
                }
                else
                {
                    model.IsSelected = false;
                }

                Models.Add(model);
            }
            ViewBag.RoleName = role.Name;
            //ViewBag.RoleId = roleId;
            return View(Models);





        }



        [HttpPost]
        public async Task<IActionResult> EditUsersRole(List<EditUsersRoleViewModel> model, string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
            {
                return View("../Error/NotFound", $"The role must be exist and not empty in Url");

            }
            var role = await this.roleManager.FindByIdAsync(roleId);
            if (role is null)
            {
                return View("../Error/NotFound", $"The role Id : {role.Id} cannot be found");
            }

            // role if deja affectté et in model is select il faut le supprimer , ou l'affecté si il est selecté au model mais non affecté before

            IdentityResult result = null;

            for (int i = 0; i < model.Count; i++)
            {
                AppUser user = await userManager.FindByIdAsync(model[i].UserId);

                if (await userManager.IsInRoleAsync(user, role.Name) && !model[i].IsSelected)
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else if (!(await userManager.IsInRoleAsync(user, role.Name)) && model[i].IsSelected)
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
            }

            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }
            return RedirectToAction("Edit", new { id = roleId });

        }


    }
}

ReservationApp/ReservationApp/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReservationApp.Models;
using ReservationApp.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationApp.Controllers
{
    //[Authorize(Roles = "Admin,User")]
    [AllowAnonymous]

    public class ServiceController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public ServiceController(AppDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }



        [AllowAnonymous]
        // GET: ServiceController/Index
        public ActionResult Index()
        {
            var services = _context.Services.ToList();
            return View(services);
        }

        // GET: ServiceController/List
        public ActionResult List()
        {
            IEnumerable<Service> services = _context.Services.ToList();
            return View(services);
        }

        // GET: ServiceController/Details/5
        public ActionResult Details(int id)
        {
            var service = _context.Services.Find(id);

            return View(service);
        }

        // GET: ServiceController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: ServiceController/Create
        [HttpPost]
        public ActionResult Create(ServiceCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if(model.Image != null)
                {
                    string extFile = Path.GetExtension(model.Image.FileName);
                    if (extFile != ".jpg" && extFile != ".png")
                    {
                        ModelState.AddModelError(" ", "Invalid File Format");
                        return View(model);
                    }
                    string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid()+"_"+model.Image.FileName;
                    string path = Path.Combine(uploadsFolder, uniqueFileName); //wwwroot/images/5656788889999nails.jpg
                    
                    // destroy the file (image service)
                    using(var fileStream = new FileStream (path, FileMode.Create))
                    {
                        model.Image.CopyTo(fileStream);

                    }

                  


                }

                Service service = new Service()
                {
                    Name = model.Name,
                    Price = model.Price,
                    Details = model.Details,
                    //TotalAgentsActif=model.TotalAgentsActif,
                    ImagePath = uniqueFileName

                };
                _context.Services.Add(service);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);

        }

        // GET: ServiceController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id is null)
            {
                return View("../Error/NotFound", "Please add the service Id in URL");
            }
            var service = _context.Services.Find(id);
            if (service is null)
            {
                return View("../Error/NotFound", $"The service Id : {id} cannot be found");
            }

            ServiceEditViewModel model = new ServiceEditViewModel()
            {
                Id = service.Id,
                Name = service.Name,
                Price = service.Price,
                Details = service.Details,
                ImagePath = service.ImagePath
            };


            return View(model);
        }

        // POST: ServiceController/Edit
        [HttpPost]
        public ActionResult Edit(ServiceEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Service service = _context.Services.Find(model.Id);
                service.Name = model.Name;
                service.Price = model.Price;
                service.Details = model.Details;
               

                string uniqueFileName = null;
                if (model.Image != null)
                {
                    string extFile = Path.GetExtension(model.Image.FileName);
                    if(extFile != ".jpg" && extFile != ".png")
                    {
                        ModelState.AddModelError(" ", "Invalid File Format");
                        return View(model);
                    }
                    string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid() + "_" + model.Image.FileName;
                    string path = Path.Combine(uploadsFolder, uniqueFileName); //wwwroot/images/5656788889999nails.jpg
                    // destroy the file (image service)
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        model.Image.CopyTo(fileStream);

                    }

                    // delete old image from wwwroot/images

                    if (service.ImagePath != null)
                    {
                        string oldImageService = Path.Combine(_hostingEnvironment.WebRootPath, "images", service.ImagePath);
                        System.IO.File.Delete(oldImageService);
                    }
                    service.ImagePath = uniqueFileName;
                }

             
                _context.Services.Update(service);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);

        }

        // GET: ServiceController/Delete/5
        public ActionResult Delete()
        {
            return RedirectToAction("Index");
        }

        // POST: ServiceController/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id)
        {
            var service = _context.Services.Find(id);
            if (service is null)
            {
                return View("../Error/NotFound", $"The service Id : {id} cannot be found");
            }

            _context.Remove(service);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

ReservationApp/ReservationApp/Views/Role/Create.cshtml
@model Role

@{

    ViewBag.Title = "ReservationSYS  | New Role";

}

<div class="my-2 text-left col-12">
    <h2> Create New Role</h2>
    <hr />
</div>

<form class="mx-lg-auto my-5 w-50" method="post">

    <div class="form-group">
        <label asp-for="RoleName"></label>
        <input class="form-control" asp-for="RoleName">
        <span asp-validation-for="RoleName" hidden class="small text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Add Role</button>
    <div class="text text-danger" asp-validation-summary="All"></div>
</form>

ReservationApp/ReservationApp/Views/Role/Edit.cshtml
@model EditRoleViewModel

@{

    ViewBag.Title = "ReservationSYS  | Edit Role";

}

<div class="my-2 text-left col-12">
    <h2> Edit Role Details </h2>
    <hr />
</div>

<form class="mx-lg-auto my-5 w-50" method="post">
    <input class="form-control" hidden asp-for="Id">

    <div class="form-group">
        <label asp-for="RoleName"></label>
        <input class="form-control" asp-for="RoleName">
        <span asp-validation-for="RoleName" class="small text-danger"></span>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Update</button>
    </div>

    <div>
        <div class="card" style=" margin:auto">
            <div class="card-body text-center">
                <h5 class="card-title">List Users</h5>

                @if (Model.Users.Count == 0)
                {
                    <p class="card-text">Any Users</p>
                }
                else
                {
                    <p class="card-text">
                        @foreach (string user in Model.Users)
                        {
                            @user <br />
                        }
                    </p>
                }
                <div>
                    <a asp-action="EditUsersRole" asp-route-RoleId="@Model.Id">Edit Users</a> |
                    <a asp-action="Index">Back to list</a>
                </div>
            </div>
        </div>
    </div>
    <div class="text text-danger" asp-validation-summary="All"></div>
</form>

ReservationApp/ReservationApp/Views/Role/EditUsersRole.cshtml
@model List<EditUsersRoleViewModel>
@{ 
    ViewBag.Title = "ReservationSYS | Edit UsersRole";
}



<div class="my-2 text-left col-12 ">
    <h2> Edit Users Role </h2>
    <hr />
</div>
<form class="mx-lg-auto my-5 w-50 " method="post">
    <div class="my-5">
        <div class="card">
            <div class="card-header">
                <span>Add or Remove Users from this Role</span>
                <hr />
                <input disabled value="@ViewBag.RoleName" class="form-control text-success font-weight-bold text-center" />
            </div>
            <div class="card-body">
                @for (int i = 0; i < Model.Count; i++)
                {
                    var uniqueName = "User" + i;
                    <div class="form-check m-1">
                        <input hidden asp-for="@Model[i].UserId" />
                        <input hidden asp-for="@Model[i].UserName" />
                        <input asp-for="@Model[i].IsSelected" id="@uniqueName" class="form-check-input" />
                        <label for="@uniqueName" class="form-check-label">@Model[i].UserName</label>
                    </div>

                }

            </div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Save</button> 
                <a asp-action="Edit" asp-route-id="@ViewBag.RoleId" class="btn btn-dark mx-2">Back</a>



            </div>
        </div>
    </div>
</form>

ReservationApp/ReservationApp/Views/Role/Index.cshtml
@model IEnumerable<IdentityRole>

@{
    int counter = 1;
    ViewBag.Title = "ReservationSYS  | Roles";
}

<div class="my-2 text-left col-12">
    <h2> List of Roles </h2>
    <hr />
</div>


@if (Model.Any())
{
<div class="mx-lg-auto my-5 col-12 ">
    <table id="RolesTable" class="table table-hover text-center ">
        <thead class="alert-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">@Html.DisplayNameFor(item => item.Id)</th>
                <th scope="col">@Html.DisplayNameFor(item => item.Name)</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (IdentityRole role in Model)
                {
                        <tr>
                            <td>@counter</td>
                            <td>@role.Id</td>
                            <td>@role.Name</td>

                            <td>
                                <form method="post" asp-action="Delete" asp-controller="Role" asp-route-id="@role.Id">
                                    <a class="btn btn-warning text-white btn-sm" asp-action="Edit" asp-controller="Role" asp-route-id="@role.Id">Update</a>
                                    <button type="submit" class="btn btn-secondary btn-sm" onclick="return confirm('Are you sure ??')">Delete</button>
                                </form>

                            </td>
                        </tr>
                    counter++;

                }

            }

        </tbody>
    </table>

</div>
    

}
else
{
    <div class=" col-12 my-5">

        <div class="card">
            <div class="card-header">
                No roles created yet

            </div>
            <div class="card-body">
                <h5 class="card-title">
                    Use the button bellow to create role
                </h5>
            </div>
        </div>
    </div>

}

<div class="my-5 text-center">
    <a asp-action="Create">Add New Role</a> |
    <a asp-action="Index" asp-controller="Service">Back to Home</a>
</div>




@section DTListRoles{
    <script>
        $(document).ready(function () {
            $('#RolesTable').dataTable();
        });


    </script>

}