ReservationApp/ReservationApp/Models/Reservation.cs
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationApp.Models
{
    public class Reservation
    {

        [Key]
        public int Id { get; set; }
        public DateTime CreateDate { get; set; }

        [Required(ErrorMessage = "The Date field is required !")]
        [Display(Name = "Date of Reservation")]
        public DateTime BookingDate { get; set; }

        [Required(ErrorMessage = "The Time field is required !")]
        [Display(Name = "Time of Reservation")]
        public TimeSpan BookingTime { get; set; }
        public Status Status { get; set; }

        public string UserId { get; set; }
        public virtual AppUser User { get; set; }

        [Required(ErrorMessage = "The service field is required !")]
        [Display(Name = "Service")]
        public int ServiceId { get; set; }
        public virtual Service Service { get; set; }

      
    

    }
}

ReservationApp/ReservationApp/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservationApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationApp.Controllers
{
    [Authorize]
    public class ReservationController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;
        public ReservationController(AppDbContext context, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _context = context;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }




        // GET: ReservationController
        public async Task<ActionResult> Index()
        {


            if (signInManager.IsSignedIn(User) && !User.IsInRole("Admin"))
            {
                AppUser user = await userManager.FindByEmailAsync(User.Identity.Name);
                var reservations = _context.Reservations.Include(r => r.Service).ToList().Where(r => r.UserId == user.Id).OrderBy(r => r.Status); // include pour afficher le nom de type d'objet type
                return View(reservations);
            }
            else
            {
                var reservations = _context.Reservations.Include(r => r.Service).Include(r => r.User).ToList().OrderBy(r => r.Status);
                return View(reservations);
            }

        }

        // GET: ReservationController/Details/5
        public ActionResult Details(int id)
        {
            var reservation = _context.Reservations.Find(id);

            return View(reservation);
        }

        // GET: ReservationController/Create
        public IActionResult Create()
        {
            var reservation = new Reservation();
            ViewBag.UserId = userManager.GetUserId(HttpContext.User);  // recuperer id de user en connection pour remplir la valeur de UserId comme proprietaire de cette reservation crée
            IEnumerable<Service> services = _context.Services.ToList(); // pour charger les services et les afficher sur input select
            ViewBag.Services = services;

            return View(reservation);
        }

        // POST: ReservationController/Create

        [HttpPost]
        public IActionResult Create(Reservation reservation)
        {
            var idService = reservation.ServiceId;
            var service = _context.Services.Find(idService);

            if (ModelState.IsValid)
            {
                _context.Reservations.Add(reservation);

                if(service.TotalReservConfirm < service.TotalAgentsActif)
                {
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View("../Error/NotFound", "There is no Agent avalaible ");
                }
            }

            ViewBag.UserId = userManager.GetUserId(HttpContext.User);
            IEnumerable<Service> services = _context.Services.ToList();
            ViewBag.Services = services;
            return View(reservation);
        }

        // GET: ReservationController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id is null)
            {
                return View("../Error/NotFound", "Please add the reservation Id in URL");
            }
            var reservation = _context.Reservations.Find(id);
            if (reservation is null)
            {
                return View("../Error/NotFound", $"The reservation Id : {id} cannot be found");
            }
            ViewBag.UserId = userManager.GetUserId(HttpContext.User);
            IEnumerable<Service> services = _context.Services.ToList();
            ViewBag.Services = services;
            return View(reservation);
        }

        // POST: ReservationController/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Reservation reservation)
        {

            var idUser = reservation.UserId;
            AppUser user = await userManager.FindByIdAsync(idUser);
            var idService = reservation.ServiceId;
            var service = _context.Services.Find(idService);


            if (ModelState.IsValid)
            {

                _context.Entry(reservation).State = EntityState.Modified;

                
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));

            }




            ViewBag.UserId = userManager.GetUserId(HttpContext.User);
            IEnumerable<Service> services = _context.Services.ToList();
            ViewBag.Services = services;
            return View(reservation);

        }

        // GET: ReservationController/Delete/5
        public ActionResult Delete()
        {
            return RedirectToAction("Index");
        }

        // POST: ReservationController/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int? id)
        {
            var reservation = _context.Reservations.Find(id);
            if (reservation is null)
            {
                return View("../Error/NotFound", $"The reservartion Id : {id} cannot be found");
            }

            var idUser = reservation.UserId;
            AppUser user = await userManager.FindByIdAsync(idUser);
            var idService = reservation.ServiceId;
            var service = _context.Services.Find(idService);

           
            _context.Remove(reservation);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        




    }
}

ReservationApp/ReservationApp/Views/Reservation/Create.cshtml
@inject SignInManager<AppUser> signInManager
@inject UserManager<AppUser> userManager
@model Reservation

@{

    ViewBag.Title = "BeautyCenter  | New Reservation";

}

<div class="my-2 text-left col-12">
    <h2> Create New Reservation</h2>
    <hr />
</div>

<form class="mx-lg-auto my-5 w-50" method="post">
    <input hidden class="form-control" type="datetime" asp-for="CreateDate" value="@DateTime.Now">
    <div class="form-group">
        <label asp-for="BookingDate"></label>
        <input type="datetime-local" class="form-control"
               asp-for="BookingDate"
               min="2020-06-07" max="2022-06-14">
        <span asp-validation-for="BookingDate" class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BookingTime"></label>
        <input type="time" class="form-control"
               asp-for="BookingTime"
               min="10:00" max="18:00">
        <small>Office hours are 10am to 6pm</small>
        <span asp-validation-for="BookingTime" class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ServiceId"></label>
        <select asp-for="ServiceId" class="form-control">
            <option value="">Select Type...</option>
            @foreach (Service service in ViewBag.Services)
            {
                <option value="@service.Id">@service.Name </option>
            }

        </select>
        <span asp-validation-for="Service" class="small text-danger"></span>
    </div>
    <div hidden class="form-group">
        <input class="form-control" asp-for="UserId" value="@ViewBag.UserId">
    </div>



    <button type="submit" class="btn btn-primary">Create</button>
    <div class="text text-danger" hidden asp-validation-summary="All"></div>




</form>

ReservationApp/ReservationApp/Views/Reservation/Edit.cshtml
@inject UserManager<AppUser> userManager
@inject SignInManager<AppUser> signInManager
@model Reservation

@{

    ViewBag.Title = "BeautyCenter  | Edit Reservation";

}

<div class="my-2 text-left col-12">
    <h2> Edit Reservation Details </h2>
    <hr />
</div>

@if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
{
<form class="mx-lg-auto my-5 w-50" method="post">
    <input hidden asp-for="Id">
    <input hidden asp-for="UserId">
    <div hidden class="form-group">
        <label asp-for="BookingDate"></label>
        <input type="datetime-local" class="form-control"
               asp-for="BookingDate"
               min="2020-06-07T00:00" max="2022-06-14T00:00">
        <span asp-validation-for="BookingDate" hidden class="small text-danger"></span>
    </div>
    <div hidden class="form-group">
        <label asp-for="BookingTime"></label>
        <input type="time" class="form-control"
               asp-for="BookingTime"
               min="10:00" max="18:00">
        <small>Office hours are 10am to 6pm</small>
        <span asp-validation-for="BookingTime" class="small text-danger"></span>
    </div>
    <div hidden class="form-group">
        <label asp-for="ServiceId"></label>
        <select asp-for="ServiceId" class="form-control">
            <option value="">Select Type...</option>
            @foreach (Service service in ViewBag.Services)
            {
                <option value="@service.Id">@service.Name</option>
            }

        </select>
        <span asp-validation-for="Service" hidden class="small text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Status"></label>
        <select class="form-control custom-select"
                asp-for="Status"
                asp-items="Html.GetEnumSelectList<Status>()">
            <option value="">Choose the status ...</option>
        </select>
        <span asp-validation-for="Status" class="small text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary" onclick="return confirm('Are you sure to change status  ??')">Update</button>
    <div asp-validation-summary="All" class="text-danger"></div>
</form>
}
@if (signInManager.IsSignedIn(User) && !User.IsInRole("Admin"))
{
<form class="mx-lg-auto my-5 w-50" method="post">
    <input hidden asp-for="Id">
    <input hidden asp-for="UserId">

    <div class="form-group">
        <label asp-for="BookingDate"></label>
        <input type="datetime-local" class="form-control"
               asp-for="BookingDate"
               min="2020-06-07T00:00" max="2022-06-14T00:00">
        <span asp-validation-for="BookingDate" hidden class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BookingTime"></label>
        <input type="time" class="form-control"
               asp-for="BookingTime"
               min="10:00" max="18:00">
        <small>Office hours are 10am to 6pm</small>
        <span asp-validation-for="BookingTime" class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ServiceId"></label>
        <select asp-for="ServiceId" class="form-control">
            <option value="">Select Type...</option>
            @foreach (Service service in ViewBag.Services)
            {
                <option value="@service.Id">@service.Name</option>
            }

        </select>
        <span asp-validation-for="Service" hidden class="small text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary">Update</button>
    <div asp-validation-summary="All" class="text-danger"></div>

</form>
}

ReservationApp/ReservationApp/Views/Reservation/Index.cshtml
@model IEnumerable<Reservation>


@{
    int counter = 1;
    ViewBag.Title = "BeautyCenter  | Reservations";
}

<div class="my-2 text-left col-12">
    <h2> List of Reservations </h2>
    <hr />
</div>

<div class="mx-lg-auto my-2 col-12 ">
    <table id="ReservationsTable" class="table table-hover text-center">
        <thead class="alert-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Reserved Day</th>
                <th scope="col">Reserved Time</th>
                <th scope="col">Service</th>

                @if (User.IsInRole("Admin"))
                {
                    <th scope="col">User</th>
                }

                <th scope="col">Status</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var reservation in Model)
                {
                        <tr>
                            <td>@counter</td>
                            <td>@reservation.BookingDate.ToShortDateString()</td>
                            <td>@reservation.BookingTime.ToString()</td>
                            <td>@reservation.Service.Name</td>

                            @if (User.IsInRole("Admin"))
                            {
                                <td>@reservation.User.Email </td>
                            }

                            @if (reservation.Status == Status.Pending)
                            {
                                <td class="text-primary">@reservation.Status</td>
                            }
                            @if (reservation.Status == Status.Canceled)
                            {
                                <td class="text-danger">@reservation.Status</td>
                            }
                            @if (reservation.Status == Status.Confirmed)
                            {
                                <td class="text-success">@reservation.Status</td>
                            }



                            @if (reservation.Status == Status.Pending || User.IsInRole("Admin"))
                            {
                                <td>

                                    <form method="post" asp-action="Delete" asp-controller="Reservation" asp-route-id="@reservation.Id">
                                        <a class="btn btn-warning text-white btn-sm" asp-action="Edit" asp-controller="Reservation" asp-route-id="@reservation.Id">Update</a>
                                        <button type="submit" class="btn btn-secondary btn-sm" onclick="return confirm('Are you sure to Delete ??')">Delete</button>
                                    </form>


                                </td>
                            }
                            else
                            {
                                <td>

                                    _


                                </td>
                            }

                        </tr>
                    counter++;

                }
            }


        </tbody>
    </table>
</div>


@if (User.IsInRole("User"))
{
    <div class="my-5 text-center">
        <a asp-action="Create">New Reservation</a> |
        <a asp-controller="Service" asp-action="Index">Back To Home</a>
    </div>
}
else
{
    <div class="my-5 text-center">
        <a asp-controller="Service" asp-action="Index">Back To Home</a>
    </div>
}




@section DTListReservations{
    <script>
        $(document).ready(function () {
            $('#ReservationsTable').dataTable();
        });


    </script>

}