ReservationApp/ReservationApp/Controllers/AgentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReservationApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationApp.Controllers
{
   // [Authorize(Roles = "Admin")]
    [AllowAnonymous]
    public class AgentController : Controller
    {
        

        private readonly AppDbContext _context;

        public AgentController(AppDbContext context)
        {
            _context = context;
        }

        // GET: AgentController
        public ActionResult Index()
        {
            IEnumerable<Agent> agents = _context.Agents.Include(a => a.Service).ToList();
            return View(agents);
        }

        // GET: AgentController/Delete/5
        public ActionResult Delete()
        {
            return RedirectToAction("Index");
        }

        // POST: AgentController/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id)
        {
            
            
            var agent = _context.Agents.Find(id);
            
            if (agent is null)
            {
                return View("../Error/NotFound", $"The Agent Id : {id} cannot be found");
            }
            var idService = agent.ServiceId;
            var service = _context.Services.Find(idService);

            if(agent.IsActive == true && service.TotalAgentsActif>0)
            {
                service.TotalAgentsActif--;
                _context.SaveChanges();
            }

            _context.Remove(agent);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        // GET: AgentController/Create
        public IActionResult Create()
        {
            var agent = new Agent();
            var services = _context.Services.ToList(); // pour charger les services et les afficher sur input select
            ViewBag.Services = services;

            return View(agent);
        }

        // POST: AgentController/Create
        
        [HttpPost]
        public IActionResult Create(Agent agent)
        {
            var idService = agent.ServiceId;
            var service = _context.Services.Find(idService);

            if (ModelState.IsValid)
            {
                _context.Agents.Add(agent);
                if (agent.IsActive == true)
                {
                    service.TotalAgentsActif++;
                    _context.SaveChanges();
                }
                
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            IEnumerable<Service> services = _context.Services.ToList();
            ViewBag.Services = services;
            return View(agent);
        }


        // GET: AgentController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id is null)
            {
                return View("../Error/NotFound", "Please add the agent Id in URL");
            }
            var agent = _context.Agents.Find(id);
            if (agent is null)
            {
                return View("../Error/NotFound", $"The agent Id : {id} cannot be found");
            }
            IEnumerable<Service> services = _context.Services.ToList();
            ViewBag.Services = services;
            return View(agent);
        }


        // POST: AgentController/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Agent agent)
        {
            
            var idService = agent.ServiceId;
            var service = _context.Services.Find(idService);
            var status = agent.IsActive;


            if (ModelState.IsValid)
            {

                

                if (agent.IsActive != status)
                {
                    if(agent.IsActive == true)
                    {
                        service.TotalAgentsActif++;
                        _context.Entry(agent).State = EntityState.Modified;
                        _context.SaveChanges();
                    }
                    else
                    {
                        service.TotalAgentsActif--;
                        _context.Entry(agent).State = EntityState.Modified;
                        _context.SaveChanges();
                    }
                }
                _context.Entry(agent).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));

            }




            IEnumerable<Service> services = _context.Services.ToList();
            ViewBag.Services = services;
            return View(agent);

        }
    }
}

ReservationApp/ReservationApp/Controllers/RoleController.cs
using ReservationApp.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using ReservationApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationApp.Controllers
{
    // [Authorize(Roles = "Admin")]
    [AllowAnonymous]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<AppUser> userManager;
        private readonly ILogger<RoleController> logger;
        public RoleController(RoleManager<IdentityRole> roleManager,
                              UserManager<AppUser> userManager,
                              ILogger<RoleController> logger)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.logger = logger;
        }

        // actions

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Role model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole()
                {
                    Name = model.RoleName
                };

                IdentityResult result = await this.roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }


        [HttpGet]
        public IActionResult Index()
        {
            var roles = this.roleManager.Roles;
            return View(roles);
        }



        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id is null)
            {
                return View("../Error/NotFound", "Please add the role Id in URL");
            }
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role is null)
            {
                return View("../Error/NotFound", $"The role Id : {id} cannot be found");
            }

            EditRoleViewModel model = new EditRoleViewModel()
            {
                Id = role.Id,
                RoleName = role.Name,
                Users = new List<string>()  // pour recuperer ds cette list les users de ce role
            };

            foreach (AppUser user in await userManager.Users.ToListAsync()) // userManager.Users is not awaitble so change to (await userManager.Users.ToListAsync())
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }
            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Edit(EditRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByIdAsync(model.Id);
                if (role is null)
                {
                    return View("../Error/NotFound", $"The role Id : {model.Id} cannot be found");
                }
                role.Name = model.RoleName;

                IdentityResult result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);

        }



        [HttpGet]
        public IActionResult Delete()
        {
            return RedirectToAction("Index");
        }



        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {

            IdentityRole role = await roleManager.FindByIdAsync(id);


            try
            {
                if (!(role is null))
                {
                    IdentityResult result = await roleManager.DeleteAsync(role);

                    if (!result.Succeeded)
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
                else
                {
                    return View("../Error/NotFound", $"The role Id : {id} cannot be found");

                }
                return RedirectToAction("Index");

            }
            catch (DbUpdateException ex)
            {
                this.logger.LogError(ex.Message);
                ViewBag.Error = "Delete Role";
                string errorMessage = role.Name + " role is in use , so this role cannot be deleted as there users in this role." +
                    "if you want to delete this role, " +
                    "please remove the users from the role and then try to delete ";
                return View("Error", errorMessage);

            }






        }


        [HttpGet]
        public async Task<IActionResult> EditUsersRole(string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
            {
                return View("../Error/NotFound", $"The role must be exist and not empty in Url");

            }
            var role = await roleManager.FindByIdAsync(roleId);
            if (role is null)
            {
                return View("../Error/NotFound", $"The role Id : {role.Id} cannot be found");
            }

            var Models = new List<EditUsersRoleViewModel>();

            foreach (var user in await userManager.Users.ToListAsync())
            {
                EditUsersRoleViewModel model = new EditUsersRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    //IsSelected = false
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.IsSelected = true;
                }
                else
                {
                    model.IsSelected = false;
                }

                Models.Add(model);
            }
            ViewBag.RoleName = role.Name;
            //ViewBag.RoleId = roleId;
            return View(Models);





        }



        [HttpPost]
        public async Task<IActionResult> EditUsersRole(List<EditUsersRoleViewModel> model, string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
            {
                return View("../Error/NotFound", $"The role must be exist and not empty in Url");

            }
            var role = await this.roleManager.FindByIdAsync(roleId);
            if (role is null)
            {
                return View("../Error/NotFound", $"The role Id : {role.Id} cannot be found");
            }

            // role if deja affectté et in model is select il faut le supprimer , ou l'affecté si il est selecté au model mais non affecté before

            IdentityResult result = null;

            for (int i = 0; i < model.Count; i++)
            {
                AppUser user = await userManager.FindByIdAsync(model[i].UserId);

                if (await userManager.IsInRoleAsync(user, role.Name) && !model[i].IsSelected)
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else if (!(await userManager.IsInRoleAsync(user, role.Name)) && model[i].IsSelected)
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
            }

            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }
            return RedirectToAction("Edit", new { id = roleId });

        }


    }
}

ReservationApp/ReservationApp/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> signInManager
@inject UserManager<AppUser> userManager



<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <!-- CSS only -->
    <environment include="Development">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

        @*<link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/jquery.js"></script>
        <script href="~/lib/bootstrap/js/bootstrap.js" rel="stylesheet"></script>*@

        @*Datatable*@
        <link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet" />
        <script src="~/lib/datatables/js/jquery.dataTables.js"></script>

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
              integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-suppress-fallback-integrity="true">


        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>


    </environment>

</head>


<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark  ">

            <a class="navbar-brand" asp-action="index" asp-controller="Service">
                <img asp-append-version="true" src="~/images/B3.png" class="align-self-md-center" >
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

          

                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button">Manage Reservations</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Reservation">Reservations</a>
                                <a class="dropdown-item" asp-action="List" asp-controller="Service">Services</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Agent">Agents</a>
                            </div>
                        </li>


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button">Manage Users</a>
                            <hr />
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Role">Roles</a>
                                <a class="dropdown-item" asp-action="ListUsers" asp-controller="Account">Users</a>
                            </div>
                        </li>



                    }
                    @if (signInManager.IsSignedIn(User) && !User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button">Manage Reservations</a>
                            <hr />
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Reservation">Reservations</a>
                                <a class="dropdown-item" asp-action="Create" asp-controller="Reservation">New Reservation</a>
                            </div>
                        </li>



                    }


                </ul>
                <ul class="navbar-nav ">

                    @if (signInManager.IsSignedIn(User))
                    {
                        string FullName = null;
                        AppUser user = await userManager.FindByEmailAsync(User.Identity.Name);

                        @if (user != null & !string.IsNullOrEmpty(user.FirstName) & !string.IsNullOrEmpty(user.LastName))
                        {
                            FullName = user.FirstName.Trim().ToUpper() + " " + user.LastName.Trim().ToLower();

                        }
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button">@user.Email</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-route-id="@user.Id" asp-action="EditAccount" asp-controller="Account">Edit Account</a>
                            <div>
                                <ul class="navbar nav">
                                    <li class="nav-item ">
                                        <form asp-action="Logout" asp-controller="Account" method="post">
                                            <button type="submit" class="btn btn-dark text-white" style="width:10em">
                                                Logout
                                            </button>

                                        </form>
                                    </li>

                                </ul>
                            </div>
                        </div>

                    </li>

                    }
                    else
                    {
                        <li class="nav-item ">
                            <a class="nav-link" asp-action="Register" asp-controller="Account">Register</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-action="Login" asp-controller="Account">Login</a>
                        </li>
                    }



                </ul>


                @*<form class="form-inline my-2 my-lg-0" asp-action="Search" asp-controller="Student" method="post">
                     <input class="form-control mr-sm-2" type="search" placeholder="Enter Cin" aria-label="Search">
                     <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                    </form>*@


            </div>

        </nav>

    </header>


    <section class="container">

        @RenderBody()

    </section>
    <footer class="bg-dark   text-light text-center  fixed-bottom  ">
        <p>&copy; CopyRight</p>
    </footer>

    @RenderSection(name: "CreateSectionJs", required: false)

    @RenderSection(name: "DTListUsers", required: false)
    @RenderSection(name: "DTListRoles", required: false)
    @RenderSection(name: "DTListAgents", required: false)
    @RenderSection(name: "DTListServices", required: false)
    @RenderSection(name: "DTListReservations", required: false)

</body>


</html>